version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.3.0
    steps:
      - checkout

      - restore_cache:
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm ci

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run: npm test
  deploy:
    docker:
      - image: circleci/node:10.3.0
    working_directory: ~/cloudflare-workers
    steps:
      - run:
          name: Deploy to Cloudflare
          command: ./deploy.sh


workflow:
  version: 2
  build-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master

